#!/usr/bin/env python3
"""Translate one reviewed textbook page with an OpenAI-compatible API.

The CLI and page JSON schema intentionally match the former Argos script:

    translate_page.py --input page.json --output translated.json

Translations and missing word phonetics are regenerated by the online model.
OCR data, coordinates, IDs, images, audio metadata, and existing phonetics are
preserved.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Protocol


MAX_TRANSLATION_COMPLETION_TOKENS = 131072


def configured_translation_completion_tokens() -> int:
    raw = os.getenv(
        "TRANSLATION_MAX_COMPLETION_TOKENS",
        str(MAX_TRANSLATION_COMPLETION_TOKENS),
    ).strip()
    try:
        value = int(raw)
    except ValueError as exc:
        raise RuntimeError("TRANSLATION_MAX_COMPLETION_TOKENS must be an integer") from exc
    if value < 1 or value > MAX_TRANSLATION_COMPLETION_TOKENS:
        raise RuntimeError(
            "TRANSLATION_MAX_COMPLETION_TOKENS must be between 1 and "
            f"{MAX_TRANSLATION_COMPLETION_TOKENS} for qwen3.7-flash"
        )
    return value


TRANSLATOR_SYSTEM_PROMPT = """You are a professional English-to-Chinese translator for children's English textbooks.

Translate the TARGET TEXT into natural Simplified Chinese.

You will receive CONTEXT to help resolve ambiguity.

Rules:
- Translate only TARGET TEXT.
- CONTEXT is only for understanding. Never translate extra context.
- Preserve the original meaning. Do not explain, expand, add, or omit information.
- Use concise, natural Simplified Chinese suitable for Chinese students.
- Resolve ambiguous words, pronouns, tense, phrases, and proper nouns from context.
- Use common Chinese forms for familiar names and places; never literally translate a person's name.
- Preserve all numbers, dates, times, negation, and factual information.
- Preserve punctuation meaning.
- Return only the translated Chinese text.
- Do not output labels, Markdown, JSON, notes, or explanations."""

WORD_TRANSLATOR_SYSTEM_PROMPT = """You are a professional vocabulary editor for children's English textbooks.

Translate only the TARGET WORD as it is used in the TARGET SENTENCE and CONTEXT.

Rules:
- Return a concise Simplified Chinese meaning appropriate to this exact occurrence.
- Use the sentence context to resolve part of speech and polysemy.
- Do not translate the whole sentence.
- Do not provide dictionary meanings that do not apply here.
- Preserve proper names using their common Chinese transliteration or standard Chinese name.
- Return only the Chinese meaning.
- Do not output labels, Markdown, JSON, notes, or explanations."""

REVIEWER_SYSTEM_PROMPT = """You are a strict English-to-Chinese translation reviewer for children's textbooks.

Review the CANDIDATE translation of TARGET TEXT using CONTEXT only for disambiguation.
Check omissions, additions, mistranslation, polysemy, names, numbers, dates, times, negation,
pronouns, serious number errors, natural Chinese, and information not present in the source.

Return exactly one JSON object matching the supplied schema.

Rules:
- Return only actual errors. If the candidate is correct, return an empty issues array.
- Each issue must identify the target field and provide a concise correction.
- Do not repeat correct candidate text.
- Never use Markdown or a code fence."""

# The original single-item prompts above remain unchanged for compatibility
# with existing callers and tests. Page translation uses these protocol
# wrappers so one request can cover all sentence and word items while keeping
# the same translation and review rules.
BATCH_TRANSLATOR_SYSTEM_PROMPT = (
    TRANSLATOR_SYSTEM_PROMPT
    + "\n\n"
    + WORD_TRANSLATOR_SYSTEM_PROMPT
    + "\n\n"
    + "For this page-level request, translate every sentence and every listed word. "
    + "Override the single-item plain-text output format and return exactly one JSON object: "
    + '{"segments":[{"id":"segment id","translation":"...","words":[{"id":"word id","meaning":"...","phonetic":"..."}]}]}. '
    + "Keep every supplied segment and word ID exactly once, in any order. "
    + "For each word, use the grammatical role and meaning of that exact word occurrence in target_text, and return a standalone Chinese dictionary-style gloss for that word. Do not return the meaning of a nearby word, the action performed by the sentence, or a translation of the whole sentence; when the word is a noun, keep it as a noun meaning rather than converting it to a nearby verb. "
    + "For every word, return its General American English IPA pronunciation with primary/secondary stress marks where appropriate. "
    + "Use a rhotic American pronunciation: retain post-vocalic /r/, use American /oʊ/ rather than British /əʊ/ when the dialects differ, and do not return British or non-rhotic IPA variants. "
    + "Return an empty phonetic only when the source is not pronounceable as an English word. Do not use a local dictionary or translation for phonetic. Return no Markdown, code fence, labels, explanations, or reasoning."
)
BATCH_REVIEWER_SYSTEM_PROMPT = (
    REVIEWER_SYSTEM_PROMPT
    + "\n\n"
    + "For this page-level request, review every supplied sentence translation, word meaning, and phonetic. "
    + "Return exactly one JSON object with an issues array. Include only incorrect fields; if everything is acceptable, return {\"issues\":[]}. "
    + "Each issue identifies segment_id, word_id (empty for a sentence translation), field (translation, meaning, or phonetic), a short reason, and the corrected suggestion. Never repeat correct candidates. "
    + "Verify that each word meaning is a standalone lexical gloss for that exact word occurrence, matches its grammatical role in target_text, and is not merely another word or nearby action from the sentence. If a candidate is a nearby verb/action instead of the target word's sense, mark it failed and correct it. "
    + "Check that every phonetic is the General American English IPA pronunciation of the exact English word, including stress where appropriate. "
    + "Reject British/non-rhotic variants when pronunciations differ; require post-vocalic /r/ and American /oʊ/ rather than British /əʊ/. "
    + "Correct an omitted, dialect-mismatched, or otherwise incorrect phonetic when you can determine it. Keep reasons brief and suggestions limited to the corrected field. Never output reasoning, Markdown, or a code fence."
)

LOCAL_TRANSLATOR_SYSTEM_PROMPT = """You are a deterministic translation engine for children's English textbooks.

Return ONLY protocol lines. Never return JSON, Markdown, code fences, labels, explanations, notes, or reasoning.

Output protocol:
S<TAB>segment_index<TAB>Chinese sentence translation
W<TAB>segment_index<TAB>word_index<TAB>Chinese word meaning<TAB>General American IPA

Rules:
- Output exactly one S line for every supplied SEGMENT.
- Output exactly one W line for every supplied WORD.
- Copy segment_index and word_index exactly.
- Never add, omit, merge, duplicate, or renumber any item.
- Do not output source/business IDs.
- Do not put TAB or newline characters inside translation, meaning, or phonetic fields.
- Translate only the target sentence, using context only to resolve ambiguity.
- Use concise natural Simplified Chinese suitable for Chinese students.
- Preserve negation, names, numbers, dates, times, and factual information.
- Each word meaning must be a standalone Chinese dictionary-style gloss for that exact occurrence and grammatical role.
- Do not translate the whole sentence as a word meaning.
- For every pronounceable English word, return General American English IPA with stress where appropriate.
- Use rhotic American pronunciation and American /oʊ/ rather than British /əʊ/ when dialects differ.
- Use an empty final phonetic field only when the source is not pronounceable as an English word.

Example:
S<TAB>0<TAB>它是什么颜色？
W<TAB>0<TAB>0<TAB>什么<TAB>wʌt
W<TAB>0<TAB>1<TAB>颜色<TAB>ˈkʌlər
"""

LOCAL_REVIEWER_SYSTEM_PROMPT = """You are a deterministic reviewer for children's English textbook translations.

Return ONLY protocol lines. Never return JSON, Markdown, code fences, labels, explanations, notes, or reasoning.

If everything is acceptable, return exactly:
OK

If there are errors, return one correction per line:
S<TAB>segment_index<TAB>translation<TAB>short reason<TAB>corrected translation
W<TAB>segment_index<TAB>word_index<TAB>meaning<TAB>short reason<TAB>corrected meaning
W<TAB>segment_index<TAB>word_index<TAB>phonetic<TAB>short reason<TAB>corrected General American IPA

Rules:
- Never output OK together with correction lines.
- Use only supplied temporary zero-based indexes.
- Do not output source/business IDs.
- Do not put TAB or newline characters inside reason or suggestion fields.
- Include only actual errors.
- Check omissions, additions, mistranslation, polysemy, names, numbers, dates, times, negation, pronouns, natural Chinese, and unsupported information.
- Check every word meaning against that exact occurrence and grammatical role.
- Check General American IPA, including stress, rhotic /r/, and American /oʊ/ where applicable.
"""

SINGLE_REVIEW_SCHEMA: dict[str, Any] = {
    "type": "object",
    "additionalProperties": False,
    "properties": {
        "passed": {"type": "boolean"},
        "score": {"type": "number"},
        "issues": {"type": "array", "items": {"type": "string"}},
        "corrected_translation": {"type": "string"},
    },
    "required": ["passed", "score", "issues", "corrected_translation"],
}

BATCH_TRANSLATION_SCHEMA: dict[str, Any] = {
    "type": "object",
    "additionalProperties": False,
    "properties": {
        "segments": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "id": {"type": "string"},
                    "translation": {"type": "string"},
                    "words": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "additionalProperties": False,
                            "properties": {
                                "id": {"type": "string"},
                                "meaning": {"type": "string"},
                                "phonetic": {"type": "string"},
                            },
                            "required": ["id", "meaning", "phonetic"],
                        },
                    },
                },
                "required": ["id", "translation", "words"],
            },
        }
    },
    "required": ["segments"],
}

BATCH_REVIEW_SCHEMA: dict[str, Any] = {
    "type": "object",
    "additionalProperties": False,
    "properties": {
        "issues": {
            "type": "array",
            "items": {
                "type": "object",
                "additionalProperties": False,
                "properties": {
                    "segment_id": {"type": "string"},
                    "word_id": {"type": "string"},
                    "field": {"type": "string", "enum": ["translation", "meaning", "phonetic"]},
                    "reason": {"type": "string"},
                    "suggestion": {"type": "string"},
                },
                "required": ["segment_id", "word_id", "field", "reason", "suggestion"],
            },
        }
    },
    "required": ["issues"],
}

PREFIX_RE = re.compile(
    r"^(?:翻译(?:结果)?|中文(?:翻译)?|translation|chinese)\s*[:：]\s*",
    re.IGNORECASE,
)
CODE_FENCE_RE = re.compile(r"^```(?:json|text|markdown)?\s*|\s*```$", re.IGNORECASE)
THINK_RE = re.compile(r"<think>.*?</think>", re.IGNORECASE | re.DOTALL)
NUMBER_RE = re.compile(r"\d+(?:[.:/-]\d+)*")
SPACE_RE = re.compile(r"[ \t\u00a0]+")


def clean_phonetic(value: Any) -> str:
    """Normalize a model-returned IPA value without accepting explanations."""
    if not isinstance(value, str):
        return ""
    candidate = value.strip().strip("`\"'")
    if candidate.startswith("/") and candidate.endswith("/") and len(candidate) > 2:
        candidate = candidate[1:-1].strip()
    candidate = SPACE_RE.sub(" ", candidate)
    if not candidate or "*" in candidate or len(candidate) > 96:
        return ""
    # Chinese explanations, labels, and sentences are not IPA values.
    if any("\u3400" <= char <= "\u9fff" for char in candidate):
        return ""
    if candidate.casefold() in {"unknown", "n/a", "na", "none", "missing", "null"}:
        return ""
    return candidate


class GenerationBackend(Protocol):
    def generate(self, system_prompt: str, user_prompt: str, max_tokens: int) -> str:
        """Return one model completion."""


class OnlineLLMClient:
    """One OpenAI-compatible client shared by translator and reviewer calls."""

    def __init__(
        self,
        *,
        base_url: str,
        api_key: str,
        model: str,
        temperature: float = 0.1,
        connect_timeout: float = 10.0,
        read_timeout: float = 90.0,
    ) -> None:
        try:
            import httpx
            from openai import OpenAI
        except ImportError as exc:
            raise RuntimeError(
                "openai is unavailable; install requirements-translate.txt"
            ) from exc
        self.model = model
        self.temperature = temperature
        self.operation_label = "整页翻译"
        self.request_type = "page_translation"
        self.page_number: int | str | None = None
        self.attempt = 1
        self.status_callback: Callable[[str], None] | None = None
        self._stats: dict[str, float | int] = {
            "total_requests": 0,
            "total_retries": 0,
            "prompt_tokens": 0,
            "completion_tokens": 0,
            "total_tokens": 0,
            "latency_seconds": 0.0,
            "failed_requests": 0,
            "review_failures": 0,
        }
        self._client = OpenAI(
            api_key=api_key,
            base_url=base_url.rstrip("/"),
            timeout=httpx.Timeout(
                timeout=read_timeout,
                connect=connect_timeout,
                read=read_timeout,
                write=connect_timeout,
                pool=connect_timeout,
            ),
            # Translation requests are intentionally single-attempt to avoid
            # silently spending tokens on repeated whole-page requests.
            max_retries=0,
        )
        # Qwen 3.7 Flash is a mixed-thinking model; translation and review do
        # not need chain-of-thought tokens.
        self._extra_body = {"enable_thinking": False}

    def _log_usage(self, response: Any, latency: float) -> None:
        usage = getattr(response, "usage", None)
        prompt_tokens = getattr(usage, "prompt_tokens", None)
        completion_tokens = getattr(usage, "completion_tokens", None)
        total_tokens = getattr(usage, "total_tokens", None)
        stats = getattr(self, "_stats", None)
        if stats is not None:
            stats["latency_seconds"] = float(stats["latency_seconds"]) + latency
            for key, value in (
                ("prompt_tokens", prompt_tokens),
                ("completion_tokens", completion_tokens),
                ("total_tokens", total_tokens),
            ):
                if isinstance(value, int):
                    stats[key] = int(stats[key]) + value
        payload = {
            "request_type": getattr(self, "request_type", "translation"),
            "page": getattr(self, "page_number", None),
            "model": self.model,
            "latency_seconds": round(latency, 3),
            "retry_count": max(0, int(getattr(self, "attempt", 1)) - 1),
            "prompt_tokens": prompt_tokens,
            "completion_tokens": completion_tokens,
            "total_tokens": total_tokens,
        }
        print("[TRANSLATION API]", json.dumps(payload), file=sys.stderr, flush=True)

    def set_operation(self, label: str, request_type: str | None = None) -> None:
        self.operation_label = label
        if request_type:
            self.request_type = request_type

    def set_request_context(self, request_type: str, page: int | str | None, attempt: int) -> None:
        self.request_type = request_type
        self.page_number = page
        self.attempt = attempt

    def record_failure(self, request_type: str) -> None:
        if not hasattr(self, "_stats"):
            return
        self._stats["failed_requests"] = int(self._stats["failed_requests"]) + 1
        if request_type == "page_review" or request_type.endswith("_review"):
            self._stats["review_failures"] = int(self._stats["review_failures"]) + 1

    def log_summary(self) -> None:
        stats = getattr(self, "_stats", None)
        if not stats:
            return
        requests = int(stats["total_requests"])
        payload = {
            "model": self.model,
            **stats,
            "average_latency_seconds": round(
                float(stats["latency_seconds"]) / requests, 3
            ) if requests else 0,
        }
        print("[TRANSLATION SUMMARY]", json.dumps(payload), file=sys.stderr, flush=True)

    def set_status_callback(self, callback: Callable[[str], None] | None) -> None:
        self.status_callback = callback

    def _report_status(self, message: str) -> None:
        callback = getattr(self, "status_callback", None)
        if callback is not None:
            callback(message)

    def _generate(
        self,
        system_prompt: str,
        user_prompt: str,
        max_completion_tokens: int,
        *,
        schema_name: str = "",
        schema: dict[str, Any] | None = None,
    ) -> str:
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ]
        started = time.monotonic()
        self._stats["total_requests"] = int(self._stats["total_requests"]) + 1
        kwargs: dict[str, Any] = {
            "model": self.model,
            "messages": messages,
            "temperature": self.temperature,
            "max_completion_tokens": max_completion_tokens,
            "extra_body": self._extra_body,
        }
        if schema is not None:
            kwargs["response_format"] = {
                "type": "json_schema",
                "json_schema": {
                    "name": schema_name,
                    "strict": True,
                    "schema": schema,
                },
            }
        response = self._client.chat.completions.create(**kwargs)
        self._log_usage(response, time.monotonic() - started)
        if not response.choices:
            raise ValueError("translation API returned no choices")
        choice = response.choices[0]
        if getattr(choice, "finish_reason", None) in {"length", "max_tokens"}:
            raise CompletionTruncated("translation completion reached its token limit")
        content = choice.message.content
        if not isinstance(content, str) or not content.strip():
            raise ValueError("translation API returned empty content")
        return content

    def generate(self, system_prompt: str, user_prompt: str, max_tokens: int) -> str:
        return self._generate(system_prompt, user_prompt, max_tokens)

    def generate_structured(
        self,
        system_prompt: str,
        user_prompt: str,
        max_completion_tokens: int,
        *,
        schema_name: str,
        schema: dict[str, Any],
    ) -> str:
        return self._generate(
            system_prompt,
            user_prompt,
            max_completion_tokens,
            schema_name=schema_name,
            schema=schema,
        )


class LocalMLXBackend:
    """Resident MLX backend for Apple Silicon local translation."""

    def __init__(self, model_repo: str | None = None) -> None:
        try:
            from mlx_lm import generate, load
            from mlx_lm.sample_utils import make_sampler
        except ImportError as exc:
            raise RuntimeError(
                "mlx-lm is unavailable; install requirements-translate.txt"
            ) from exc
        self.model = "local-qwen3-4b-instruct-2507"
        self.model_repo = (
            model_repo
            or os.getenv("TRANSLATION_LOCAL_MODEL_REPO", "").strip()
            or "mlx-community/Qwen3-4B-Instruct-2507-4bit"
        )
        self.operation_label = "本地整页翻译"
        self.request_type = "page_translation"
        self.page_number: int | str | None = None
        self.attempt = 1
        self.status_callback: Callable[[str], None] | None = None
        try:
            self.max_tokens = int(os.getenv("LOCAL_TRANSLATION_MAX_TOKENS", "16384"))
        except ValueError as exc:
            raise RuntimeError("LOCAL_TRANSLATION_MAX_TOKENS must be an integer") from exc
        if self.max_tokens < 512:
            raise RuntimeError("LOCAL_TRANSLATION_MAX_TOKENS must be at least 512")
        started = time.monotonic()
        load_target = self.model_repo
        # After the first successful download, prefer the already cached
        # Hugging Face snapshot. This makes translation -> TTS -> translation
        # switching independent of Hub availability and avoids a transient 503
        # just because the resident MLX model had to be loaded again.
        if not Path(load_target).expanduser().exists():
            try:
                from huggingface_hub import snapshot_download
                load_target = snapshot_download(
                    repo_id=self.model_repo,
                    local_files_only=True,
                )
            except Exception:
                # First install/download still needs the normal mlx-lm Hub
                # resolution. Do not hide that error if the actual load fails.
                load_target = self.model_repo
        self._model, self._tokenizer = load(load_target)
        self._generate_fn = generate
        # Translation is a deterministic data-processing task. Greedy sampling
        # reduces JSON/ID drift compared with creative temperature sampling.
        self._sampler = make_sampler(temp=0.0)
        print(
            "[TRANSLATION LOCAL HEALTH] "
            f"model={self.model_repo} load_target={load_target} load_seconds={time.monotonic() - started:.3f}",
            file=sys.stderr,
            flush=True,
        )

    def set_operation(self, label: str, request_type: str | None = None) -> None:
        self.operation_label = label
        if request_type:
            self.request_type = request_type

    def set_request_context(self, request_type: str, page: int | str | None, attempt: int) -> None:
        self.request_type = request_type
        self.page_number = page
        self.attempt = attempt

    def set_status_callback(self, callback: Callable[[str], None] | None) -> None:
        self.status_callback = callback

    def _report_status(self, message: str) -> None:
        if self.status_callback is not None:
            self.status_callback(message)

    def record_failure(self, _request_type: str) -> None:
        return None

    def log_summary(self) -> None:
        return None

    def _prompt(self, system_prompt: str, user_prompt: str) -> str:
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ]
        apply_template = getattr(self._tokenizer, "apply_chat_template", None)
        if callable(apply_template):
            try:
                return apply_template(
                    messages,
                    tokenize=False,
                    add_generation_prompt=True,
                    enable_thinking=False,
                )
            except TypeError:
                return apply_template(
                    messages,
                    tokenize=False,
                    add_generation_prompt=True,
                )
        return f"SYSTEM:\n{system_prompt}\n\nUSER:\n{user_prompt}\n\nASSISTANT:\n"

    def generate(self, system_prompt: str, user_prompt: str, max_tokens: int) -> str:
        prompt = self._prompt(system_prompt, user_prompt)
        token_limit = min(max_tokens, self.max_tokens)
        started = time.monotonic()
        result = self._generate_fn(
            self._model,
            self._tokenizer,
            prompt=prompt,
            max_tokens=token_limit,
            sampler=self._sampler,
        )
        if not isinstance(result, str) or not result.strip():
            raise ValueError("local translation model returned empty content")
        print(
            "[TRANSLATION LOCAL] "
            + json.dumps(
                {
                    "request_type": self.request_type,
                    "page": self.page_number,
                    "model": self.model_repo,
                    "latency_seconds": round(time.monotonic() - started, 3),
                    "max_tokens": token_limit,
                },
                ensure_ascii=False,
            ),
            file=sys.stderr,
            flush=True,
        )
        return result

    def generate_structured(
        self,
        system_prompt: str,
        user_prompt: str,
        max_completion_tokens: int,
        *,
        schema_name: str,
        schema: dict[str, Any],
    ) -> str:
        structured_system = (
            system_prompt
            + "\n\nReturn only valid JSON. The JSON must match this schema exactly:\n"
            + json.dumps(schema, ensure_ascii=False, separators=(",", ":"))
        )
        return self.generate(structured_system, user_prompt, max_completion_tokens)


class CompletionTruncated(RuntimeError):
    """The provider stopped at the requested output token cap."""


@dataclass
class ReviewResult:
    passed: bool
    score: float
    issues: list[str]
    corrected_translation: str
    reviewer_failed: bool = False


@dataclass
class TranslationResult:
    translation: str
    score: float | None
    issues: list[str]
    review: str


def normalize_source_text(value: Any) -> str:
    """Collapse OCR visual line wraps without creating new sentence boundaries."""
    return SPACE_RE.sub(" ", " ".join(str(value or "").splitlines())).strip()


def _remove_thinking(value: str) -> str:
    cleaned = THINK_RE.sub("", value).strip()
    if "</think>" in cleaned.lower():
        cleaned = re.split(r"</think>", cleaned, flags=re.IGNORECASE)[-1].strip()
    return cleaned


def clean_translation(value: Any) -> str:
    text = _remove_thinking(str(value or "").strip())
    text = CODE_FENCE_RE.sub("", text).strip()
    lines = []
    for line in text.splitlines():
        line = line.strip()
        line = re.sub(r"^>\s?", "", line)
        if line:
            lines.append(line)
    text = " ".join(lines)
    while True:
        stripped = PREFIX_RE.sub("", text, count=1).strip()
        if stripped == text:
            break
        text = stripped
    return SPACE_RE.sub(" ", text).strip().strip("`")


def _clean_json_payload(value: Any) -> str:
    text = _remove_thinking(str(value or "").strip())
    text = CODE_FENCE_RE.sub("", text).strip()
    try:
        payload = json.loads(text)
        if isinstance(payload, dict):
            return json.dumps(payload, ensure_ascii=False)
    except json.JSONDecodeError:
        pass

    # Accept one object surrounded by a small amount of prose. raw_decode
    # correctly handles braces and escaped quotes inside JSON strings; no
    # speculative repairs or string replacements are made.
    decoder = json.JSONDecoder()
    last_error: json.JSONDecodeError | None = None
    for match in re.finditer(r"\{", text):
        try:
            payload, end = decoder.raw_decode(text, match.start())
        except json.JSONDecodeError as exc:
            last_error = exc
            continue
        prefix = text[: match.start()].strip()
        suffix = text[end:].strip()
        if isinstance(payload, dict) and len(prefix) <= 256 and len(suffix) <= 256:
            return json.dumps(payload, ensure_ascii=False)
    if last_error is not None:
        raise last_error
    raise ValueError("structured response does not contain a JSON object")


def parse_review(value: Any, candidate: str) -> ReviewResult:
    payload = json.loads(_clean_json_payload(value))
    if not isinstance(payload, dict):
        raise ValueError("reviewer response must be a JSON object")
    passed = payload.get("passed")
    if not isinstance(passed, bool):
        raise ValueError("reviewer passed must be boolean")
    score = payload.get("score")
    if not isinstance(score, (int, float)) or isinstance(score, bool):
        raise ValueError("reviewer score must be numeric")
    score = float(score)
    if score > 1 and score <= 100:
        score /= 100
    if score < 0 or score > 1:
        raise ValueError("reviewer score must be between 0 and 1")
    raw_issues = payload.get("issues", [])
    if not isinstance(raw_issues, list):
        raise ValueError("reviewer issues must be an array")
    issues = [str(item).strip() for item in raw_issues if str(item).strip()]
    corrected = clean_translation(payload.get("corrected_translation", ""))
    if not corrected:
        corrected = candidate
    if passed and corrected != clean_translation(candidate):
        passed = False
        issues.append("reviewer corrected the candidate")
    return ReviewResult(passed, score, issues, corrected)


def explicit_context(segment: dict[str, Any]) -> str:
    for key in ("context", "paragraph", "block_text", "block"):
        value = segment.get(key)
        if isinstance(value, str) and normalize_source_text(value):
            return normalize_source_text(value)
        if isinstance(value, dict):
            for nested_key in ("text", "content"):
                nested = value.get(nested_key)
                if isinstance(nested, str) and normalize_source_text(nested):
                    return normalize_source_text(nested)
    return ""


def target_sentence(segment: dict[str, Any]) -> str:
    sentence = segment.get("sentence")
    if isinstance(sentence, str) and normalize_source_text(sentence):
        return normalize_source_text(sentence)
    return normalize_source_text(segment.get("text", ""))


def page_context(segments: list[dict[str, Any]], index: int, max_chars: int = 2400) -> str:
    direct = explicit_context(segments[index])
    if direct:
        target = target_sentence(segments[index])
        if target and target not in direct:
            available = max(0, max_chars - len(target) - 1)
            return f"{direct[:available]}\n{target}".strip()
        return direct[:max_chars]
    texts = [target_sentence(segment) for segment in segments]
    texts = [text for text in texts if text]
    if not texts:
        return target_sentence(segments[index])
    full = "\n".join(texts)
    if len(full) <= max_chars:
        return full
    # Keep a centered page window when a page contains unusually dense text.
    chosen: list[tuple[int, str]] = []
    used = 0
    for distance in range(len(segments)):
        candidates = [index] if distance == 0 else [index - distance, index + distance]
        for current in candidates:
            if current < 0 or current >= len(segments):
                continue
            text = target_sentence(segments[current])
            if not text or used + len(text) + 1 > max_chars:
                continue
            chosen.append((current, text))
            used += len(text) + 1
    chosen.sort(key=lambda item: item[0])
    return "\n".join(text for _, text in chosen)


def sentence_prompt(context: str, target: str) -> str:
    return f"CONTEXT:\n{context}\n\nTARGET TEXT:\n{target}"


def word_prompt(context: str, sentence: str, word: str) -> str:
    return (
        f"CONTEXT:\n{context}\n\n"
        f"TARGET SENTENCE:\n{sentence}\n\n"
        f"TARGET WORD:\n{word}"
    )


def reviewer_prompt(kind: str, context: str, target: str, candidate: str) -> str:
    return (
        f"TYPE: {kind}\n\n"
        f"CONTEXT:\n{context}\n\n"
        f"TARGET TEXT:\n{target}\n\n"
        f"CANDIDATE CHINESE TRANSLATION:\n{candidate}"
    )


def _page_items(segments: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], dict[str, set[str]]]:
    """Build a stable ID-addressed page payload for both batch requests."""
    items: list[dict[str, Any]] = []
    expected: dict[str, set[str]] = {}
    seen_segments: set[str] = set()
    for index, segment in enumerate(segments):
        segment_id = str(segment.get("id", "")).strip()
        if not segment_id or segment_id in seen_segments:
            raise ValueError(f"invalid or duplicate segment id at index {index}")
        seen_segments.add(segment_id)
        sentence = target_sentence(segment)
        words: list[dict[str, str]] = []
        word_ids: set[str] = set()
        raw_words = segment.get("words", [])
        if not isinstance(raw_words, list):
            raise ValueError(f"segment {segment_id} words must be an array")
        for word_index, word in enumerate(raw_words):
            if not isinstance(word, dict):
                raise ValueError(f"segment {segment_id} word {word_index} is invalid")
            source = normalize_source_text(word.get("text", ""))
            # Older drafts may still contain punctuation-only OCR boxes.
            # Keep punctuation in target_sentence, but never send these as
            # independent word/meaning requests to the translation model.
            if not source or not any(character.isalnum() for character in source):
                continue
            word_id = str(word.get("id", "")).strip()
            if not word_id or word_id in word_ids:
                raise ValueError(f"invalid or duplicate word id in segment {segment_id}")
            word_ids.add(word_id)
            words.append(
                {
                    "id": word_id,
                    "text": source,
                    # Sending an existing value gives the reviewer context,
                    # but the apply step below never overwrites it.
                    "phonetic": str(word.get("phonetic", "") or "").strip(),
                }
            )
        expected[segment_id] = word_ids
        items.append(
            {
                "id": segment_id,
                "context": page_context(segments, index),
                "target_text": sentence,
                "words": words,
            }
        )
    return items, expected


def batch_translation_prompt(items: list[dict[str, Any]]) -> str:
    return (
        "Translate every supplied textbook-page item. Each item has its own context; do not translate context. "
        "Translate target_text as a sentence and each word only in its target sentence. Return General American English IPA for every word, even when the input phonetic is blank. Use rhotic American pronunciation, not British IPA. Existing phonetics are reference values only and must be preserved by the application.\n\n"
        "PAGE ITEMS:\n"
        + json.dumps(items, ensure_ascii=False, separators=(",", ":"))
        + "\n\nReturn the exact page JSON shape required by the system instructions."
    )


def batch_review_prompt(items: list[dict[str, Any]]) -> str:
    return (
        "Review every supplied textbook-page candidate. Use each item's context only for disambiguation. "
        "Correct omissions, additions, mistranslations, names, numbers, negation, and word polysemy.\n\n"
        "PAGE CANDIDATES:\n"
        + json.dumps(items, ensure_ascii=False, separators=(",", ":"))
        + "\n\nReturn the exact page review JSON shape required by the system instructions."
    )



STRUCTURAL_ID_RE = re.compile(r"^p0*(\d+)-s0*(\d+)(?:-w0*(\d+))?$", re.IGNORECASE)


def _canonical_structural_id(value: Any) -> str | None:
    text = str(value or "").strip()
    match = STRUCTURAL_ID_RE.fullmatch(text)
    if not match:
        return None
    page = int(match.group(1))
    segment = int(match.group(2))
    word = match.group(3)
    if word is None:
        return f"p{page}-s{segment}"
    return f"p{page}-s{segment}-w{int(word)}"


def _resolve_expected_id(value: Any, expected_ids: set[str], label: str) -> str:
    """Resolve only exact IDs or structurally identical IDs with leading zeros.

    Examples:
      p053-s012 -> p53-s12
      p053-s012-w002 -> p53-s12-w2

    No fuzzy edit distance, index correction, or positional guessing is allowed.
    """
    raw = str(value or "").strip()
    if raw in expected_ids:
        return raw
    canonical = _canonical_structural_id(raw)
    if canonical is None:
        raise ValueError(f"batch translator returned unexpected {label} id: {raw}")
    matches = [
        candidate
        for candidate in expected_ids
        if _canonical_structural_id(candidate) == canonical
    ]
    if len(matches) != 1:
        raise ValueError(f"batch translator returned unexpected {label} id: {raw}")
    return matches[0]


class LocalStructureError(ValueError):
    """Local-model output is syntactically valid enough to inspect but structurally unusable."""


def local_translation_prompt(items: list[dict[str, Any]]) -> str:
    payload = {
        "segment_count": len(items),
        "items": [
            {
                "segment_index": segment_index,
                "context": item["context"],
                "target_text": item["target_text"],
                "word_count": len(item["words"]),
                "words": [
                    {
                        "word_index": word_index,
                        "text": word["text"],
                        "phonetic": word.get("phonetic", ""),
                    }
                    for word_index, word in enumerate(item["words"])
                ],
            }
            for segment_index, item in enumerate(items)
        ],
    }
    return (
        "Translate the following textbook data. "
        "Use only the temporary numeric indexes shown in the payload. "
        "Never output or reconstruct any source/business IDs. "
        "Return every segment_index and word_index exactly once.\n\n"
        + json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    )


def parse_local_translation(
    value: Any,
    items: list[dict[str, Any]],
) -> dict[str, dict[str, Any]]:
    payload = json.loads(_clean_json_payload(value))
    if not isinstance(payload, dict) or set(payload) != {"segments"}:
        raise LocalStructureError("local translator response must contain only a segments array")
    raw_segments = payload["segments"]
    if not isinstance(raw_segments, list):
        raise LocalStructureError("local translator segments must be an array")
    if len(raw_segments) != len(items):
        raise LocalStructureError(
            f"local translator segment count mismatch: got {len(raw_segments)}, want {len(items)}"
        )

    by_segment_index: dict[int, dict[str, Any]] = {}
    for raw_segment in raw_segments:
        required = {"segment_index", "translation", "words"}
        if not isinstance(raw_segment, dict) or set(raw_segment) != required:
            raise LocalStructureError("local translator segment has an invalid shape")
        segment_index = raw_segment.get("segment_index")
        if not isinstance(segment_index, int) or isinstance(segment_index, bool):
            raise LocalStructureError("local translator segment_index must be an integer")
        if segment_index < 0 or segment_index >= len(items):
            raise LocalStructureError(
                f"local translator segment_index out of range: {segment_index}"
            )
        if segment_index in by_segment_index:
            raise LocalStructureError(
                f"local translator duplicate segment_index: {segment_index}"
            )
        by_segment_index[segment_index] = raw_segment

    expected_segment_indexes = set(range(len(items)))
    if set(by_segment_index) != expected_segment_indexes:
        raise LocalStructureError(
            "local translator segment indexes do not exactly match the input"
        )

    result: dict[str, dict[str, Any]] = {}
    for segment_index, item in enumerate(items):
        raw_segment = by_segment_index[segment_index]
        translation = clean_translation(raw_segment.get("translation", ""))
        if not translation:
            raise ValueError(
                f"local translator returned empty translation at segment {segment_index}"
            )
        raw_words = raw_segment.get("words")
        if not isinstance(raw_words, list):
            raise LocalStructureError(
                f"local translator words must be an array at segment {segment_index}"
            )
        expected_words = item["words"]
        if len(raw_words) != len(expected_words):
            raise LocalStructureError(
                f"local translator word count mismatch at segment {segment_index}: "
                f"got {len(raw_words)}, want {len(expected_words)}"
            )

        by_word_index: dict[int, dict[str, Any]] = {}
        for raw_word in raw_words:
            required_word = {"word_index", "meaning", "phonetic"}
            if not isinstance(raw_word, dict) or set(raw_word) != required_word:
                raise LocalStructureError(
                    f"local translator word at segment {segment_index} has an invalid shape"
                )
            word_index = raw_word.get("word_index")
            if not isinstance(word_index, int) or isinstance(word_index, bool):
                raise LocalStructureError(
                    f"local translator word_index must be an integer at segment {segment_index}"
                )
            if word_index < 0 or word_index >= len(expected_words):
                raise LocalStructureError(
                    f"local translator word_index out of range: {segment_index}:{word_index}"
                )
            if word_index in by_word_index:
                raise LocalStructureError(
                    f"local translator duplicate word_index: {segment_index}:{word_index}"
                )
            by_word_index[word_index] = raw_word

        expected_word_indexes = set(range(len(expected_words)))
        if set(by_word_index) != expected_word_indexes:
            raise LocalStructureError(
                f"local translator word indexes do not exactly match segment {segment_index}"
            )

        words: dict[str, dict[str, str]] = {}
        for word_index, source_word in enumerate(expected_words):
            raw_word = by_word_index[word_index]
            meaning = clean_translation(raw_word.get("meaning", ""))
            if not meaning:
                raise ValueError(
                    f"local translator returned empty meaning at {segment_index}:{word_index}"
                )
            phonetic_value = raw_word.get("phonetic")
            if not isinstance(phonetic_value, str):
                raise ValueError(
                    f"local translator returned invalid phonetic at {segment_index}:{word_index}"
                )
            words[str(source_word["id"])] = {
                "meaning": meaning,
                "phonetic": clean_phonetic(phonetic_value),
            }
        result[str(item["id"])] = {
            "translation": translation,
            "words": words,
        }
    return result


def local_review_prompt(
    items: list[dict[str, Any]],
    candidates: dict[str, dict[str, Any]],
) -> str:
    payload = {
        "segment_count": len(items),
        "segments": [
            {
                "segment_index": segment_index,
                "context": item["context"],
                "target_text": item["target_text"],
                "candidate_translation": candidates[item["id"]]["translation"],
                "word_count": len(item["words"]),
                "words": [
                    {
                        "word_index": word_index,
                        "text": word["text"],
                        "candidate_meaning": candidates[item["id"]]["words"][word["id"]]["meaning"],
                        "candidate_phonetic": candidates[item["id"]]["words"][word["id"]]["phonetic"],
                    }
                    for word_index, word in enumerate(item["words"])
                ],
            }
            for segment_index, item in enumerate(items)
        ],
    }
    return (
        "Review the following textbook translation candidates. "
        "Refer to content only by the temporary zero-based segment_index and word_index. "
        "Never output or reconstruct source/business IDs.\n\n"
        + json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    )


def parse_local_review(
    value: Any,
    items: list[dict[str, Any]],
    candidates: dict[str, dict[str, Any]],
) -> dict[str, dict[str, Any]]:
    payload = json.loads(_clean_json_payload(value))
    if not isinstance(payload, dict) or set(payload) != {"issues"}:
        raise LocalStructureError("local reviewer response must contain only an issues array")
    issues = payload["issues"]
    if not isinstance(issues, list):
        raise LocalStructureError("local reviewer issues must be an array")

    result = fallback_review(candidates)
    seen: set[tuple[int, int, str]] = set()
    for raw in issues:
        required = {"segment_index", "word_index", "field", "reason", "suggestion"}
        if not isinstance(raw, dict) or set(raw) != required:
            raise LocalStructureError("local reviewer issue has an invalid shape")
        segment_index = raw["segment_index"]
        word_index = raw["word_index"]
        field = str(raw["field"]).strip()
        reason = str(raw["reason"]).strip()
        suggestion = str(raw["suggestion"]).strip()
        if not isinstance(segment_index, int) or isinstance(segment_index, bool):
            raise LocalStructureError("local reviewer segment_index must be an integer")
        if not isinstance(word_index, int) or isinstance(word_index, bool):
            raise LocalStructureError("local reviewer word_index must be an integer")
        if segment_index < 0 or segment_index >= len(items):
            raise LocalStructureError(f"local reviewer segment_index out of range: {segment_index}")
        if field not in {"translation", "meaning", "phonetic"} or not reason:
            raise ValueError("local reviewer issue has an invalid field or reason")

        item = items[segment_index]
        segment_id = str(item["id"])
        if field == "translation":
            if word_index != -1:
                raise LocalStructureError("local sentence translation issue must use word_index=-1")
            correction = clean_translation(suggestion)
            if not correction:
                raise ValueError("local sentence translation correction must not be empty")
            result[segment_id]["translation"] = correction
            result[segment_id]["issues"].append(reason)
            result[segment_id]["passed"] = False
        else:
            if word_index < 0 or word_index >= len(item["words"]):
                raise LocalStructureError(
                    f"local reviewer word_index out of range: {segment_index}:{word_index}"
                )
            word_id = str(item["words"][word_index]["id"])
            word_result = result[segment_id]["words"][word_id]
            if field == "meaning":
                correction = clean_translation(suggestion)
                if not correction:
                    raise ValueError(
                        f"local word meaning correction must not be empty: {segment_index}:{word_index}"
                    )
                word_result["meaning"] = correction
            else:
                correction = clean_phonetic(suggestion)
                if not correction:
                    raise ValueError(
                        f"local phonetic correction must not be empty: {segment_index}:{word_index}"
                    )
                word_result["phonetic"] = correction
            word_result["issues"].append(reason)
            result[segment_id]["passed"] = False

        issue_key = (segment_index, word_index, field)
        if issue_key in seen:
            raise LocalStructureError("local reviewer returned a duplicate issue")
        seen.add(issue_key)
    return result


def _is_local_retryable_structure_error(exc: Exception) -> bool:
    # Local inference may regenerate the same whole-page request once when the
    # output itself is malformed/truncated. Semantic/count mismatches remain
    # hard failures so we never guess how to realign textbook content.
    if isinstance(exc, (json.JSONDecodeError, CompletionTruncated, LocalStructureError)):
        return True
    return isinstance(exc, ValueError) and str(exc) == "structured response does not contain a JSON object"


def _local_structured_call(
    backend: LocalMLXBackend,
    system_prompt: str,
    prompt: str,
    *,
    kind: str,
    page: int | str | None,
    parser: Any,
    schema: dict[str, Any],
    max_completion_tokens: int,
) -> Any:
    """Run one local whole-page request and regenerate malformed JSON once."""
    last_error: Exception | None = None
    for attempt in (1, 2):
        raw: str | None = None
        try:
            _set_request_context(backend, kind, page, attempt)
            retry_instruction = ""
            if attempt == 2:
                retry_instruction = (
                    "\n\nPREVIOUS OUTPUT WAS INVALID OR TRUNCATED JSON. "
                    "Regenerate the entire same request from scratch. Return ONLY one "
                    "complete JSON object. Keep every array length and position exactly "
                    "the same as the input. Do not output IDs."
                )
            raw = _generate_once(
                backend,
                system_prompt + retry_instruction,
                prompt,
                max_completion_tokens,
                schema_name=kind,
                schema=schema,
            )
            return parser(raw)
        except Exception as exc:
            last_error = exc
            log_failure(
                kind=kind,
                target="local_page",
                context="",
                error=exc,
                attempt=attempt,
                page=page,
                model=getattr(backend, "model", ""),
                raw=raw,
            )
            if attempt == 1 and _is_local_retryable_structure_error(exc):
                print(
                    json.dumps(
                        {
                            "event": "status",
                            "message": "本地模型结构化输出无效，正在仅重生成本页一次",
                        },
                        ensure_ascii=False,
                    ),
                    flush=True,
                )
                continue
            raise
    raise last_error or RuntimeError("local structured generation failed")


def parse_batch_translation(value: Any, expected: dict[str, set[str]]) -> dict[str, dict[str, Any]]:
    payload = json.loads(_clean_json_payload(value))
    if not isinstance(payload, dict) or not isinstance(payload.get("segments"), list):
        raise ValueError("batch translator response must contain a segments array")
    result: dict[str, dict[str, Any]] = {}
    for raw in payload["segments"]:
        if not isinstance(raw, dict):
            raise ValueError("batch translator segment must be an object")
        raw_segment_id = str(raw.get("id", "")).strip()
        segment_id = _resolve_expected_id(raw_segment_id, set(expected), "segment")
        if segment_id in result:
            raise ValueError(f"batch translator returned duplicate segment id: {raw_segment_id}")
        translation = clean_translation(raw.get("translation", ""))
        if not translation:
            raise ValueError(f"batch translator returned empty translation: {segment_id}")
        raw_words = raw.get("words", [])
        if not isinstance(raw_words, list):
            raise ValueError(f"batch translator words must be an array: {segment_id}")
        words: dict[str, dict[str, str]] = {}
        for word in raw_words:
            if not isinstance(word, dict):
                raise ValueError(f"batch translator word must be an object: {segment_id}")
            raw_word_id = str(word.get("id", "")).strip()
            word_id = _resolve_expected_id(raw_word_id, expected[segment_id], "word")
            if word_id in words:
                raise ValueError(f"batch translator returned duplicate word id: {raw_word_id}")
            meaning = clean_translation(word.get("meaning", ""))
            if not meaning:
                raise ValueError(f"batch translator returned empty meaning: {word_id}")
            if "phonetic" not in word or not isinstance(word.get("phonetic"), str):
                raise ValueError(f"batch translator returned invalid phonetic: {word_id}")
            words[word_id] = {
                "meaning": meaning,
                "phonetic": clean_phonetic(word.get("phonetic", "")),
            }
        if set(words) != expected[segment_id]:
            raise ValueError(f"batch translator word IDs do not match segment {segment_id}")
        result[segment_id] = {"translation": translation, "words": words}
    if set(result) != set(expected):
        raise ValueError("batch translator segment IDs do not match the input page")
    return result


def parse_batch_review(
    value: Any,
    candidates: dict[str, dict[str, Any]],
    expected: dict[str, set[str]],
) -> dict[str, dict[str, Any]]:
    payload = json.loads(_clean_json_payload(value))
    if not isinstance(payload, dict) or set(payload) != {"issues"}:
        raise ValueError("batch reviewer response must contain only an issues array")
    if not isinstance(payload["issues"], list):
        raise ValueError("batch reviewer issues must be an array")

    # Start from the translator's validated page and overlay only the fields
    # the reviewer explicitly identifies as incorrect.
    result: dict[str, dict[str, Any]] = {
        segment_id: {
            "translation": candidate["translation"],
            "issues": [],
            "passed": True,
            "words": {
                word_id: {
                    "meaning": word["meaning"],
                    "phonetic": word["phonetic"],
                    "issues": [],
                }
                for word_id, word in candidate["words"].items()
            },
        }
        for segment_id, candidate in candidates.items()
    }

    seen: set[tuple[str, str, str]] = set()
    for raw in payload["issues"]:
        required = {"segment_id", "word_id", "field", "reason", "suggestion"}
        if not isinstance(raw, dict) or set(raw) != required:
            raise ValueError("batch reviewer issue has an invalid shape")
        raw_segment_id = str(raw["segment_id"]).strip()
        try:
            segment_id = _resolve_expected_id(raw_segment_id, set(expected), "segment")
        except ValueError as exc:
            raise ValueError(f"batch reviewer returned unexpected segment id: {raw_segment_id}") from exc
        raw_word_id = str(raw["word_id"]).strip()
        word_id = raw_word_id
        field = str(raw["field"]).strip()
        reason = str(raw["reason"]).strip()
        suggestion = str(raw["suggestion"]).strip()
        if field not in {"translation", "meaning", "phonetic"} or not reason:
            raise ValueError("batch reviewer issue has an invalid field or reason")
        if field == "translation":
            if word_id:
                raise ValueError("sentence translation issue must not include a word ID")
            correction = clean_translation(suggestion)
            if not correction:
                raise ValueError("sentence translation correction must not be empty")
            result[segment_id]["translation"] = correction
            result[segment_id]["issues"].append(reason)
            result[segment_id]["passed"] = False
        else:
            try:
                word_id = _resolve_expected_id(raw_word_id, expected[segment_id], "word")
            except ValueError as exc:
                raise ValueError(f"batch reviewer returned unexpected word id: {raw_word_id}") from exc
            word_result = result[segment_id]["words"][word_id]
            if field == "meaning":
                correction = clean_translation(suggestion)
                if not correction:
                    raise ValueError(f"word meaning correction must not be empty: {word_id}")
                word_result["meaning"] = correction
            else:
                correction = clean_phonetic(suggestion)
                word_result["phonetic"] = correction
            word_result["issues"].append(reason)
            result[segment_id]["passed"] = False
        issue_key = (segment_id, word_id, field)
        if issue_key in seen:
            raise ValueError("batch reviewer returned a duplicate issue")
        seen.add(issue_key)
    return result


def _set_request_context(
    backend: GenerationBackend, kind: str, page: int | str | None, attempt: int
) -> None:
    setter = getattr(backend, "set_request_context", None)
    if callable(setter):
        setter(kind, page, attempt)


def _generate_once(
    backend: GenerationBackend,
    system_prompt: str,
    prompt: str,
    max_completion_tokens: int,
    *,
    schema_name: str | None,
    schema: dict[str, Any] | None,
) -> str:
    structured = getattr(backend, "generate_structured", None)
    if schema is not None and callable(structured):
        return structured(
            system_prompt,
            prompt,
            max_completion_tokens,
            schema_name=schema_name or "translation_result",
            schema=schema,
        )
    return backend.generate(system_prompt, prompt, max_completion_tokens)


def _call_once(
    backend: GenerationBackend,
    system_prompt: str,
    prompt: str,
    *,
    kind: str,
    page: int | str | None,
    parser: Any,
    max_completion_tokens: int,
    schema_name: str | None = None,
    schema: dict[str, Any] | None = None,
) -> Any:
    token_budget = max_completion_tokens
    set_operation = getattr(backend, "set_operation", None)
    set_status_callback = getattr(backend, "set_status_callback", None)
    if callable(set_operation):
        label = {"page_translation": "整页翻译", "page_review": "整页审核"}.get(
            kind, kind.replace("_", " ")
        )
        try:
            set_operation(label, request_type=kind)
        except TypeError:
            set_operation(label)
    if callable(set_status_callback):
        set_status_callback(
            lambda message: print(
                json.dumps({"event": "status", "message": message}, ensure_ascii=False),
                flush=True,
            )
        )
    report_status = getattr(backend, "_report_status", None)
    raw: str | None = None
    try:
        _set_request_context(backend, kind, page, 1)
        if callable(report_status):
            report_status(f"正在请求{getattr(backend, 'operation_label', kind)}模型")
        raw = _generate_once(
            backend,
            system_prompt,
            prompt,
            token_budget,
            schema_name=schema_name,
            schema=schema,
        )
        return parser(raw)
    except Exception as exc:
        log_failure(
            kind=kind,
            target="page",
            context="",
            error=exc,
            attempt=1,
            page=page,
            model=getattr(backend, "model", ""),
            raw=raw,
        )
        recorder = getattr(backend, "record_failure", None)
        if callable(recorder):
            recorder(kind)
        raise
    finally:
        if callable(set_status_callback):
            set_status_callback(None)


def log_translation(
    *, kind: str, target: str, context: str, result: TranslationResult, word: str = ""
) -> None:
    payload: dict[str, Any] = {
        "request_type": f"{kind}_translation",
        "source_length": len(target),
        "context_length": len(context),
        "translation_length": len(result.translation),
        "review": result.review,
    }
    if result.score is not None:
        payload["score"] = round(result.score, 4)
    if result.issues:
        payload["issues"] = result.issues
    if os.getenv("TRANSLATION_DEBUG", "").strip().lower() in {"1", "true", "yes"}:
        payload["source_preview"] = target[:120]
        payload["translation_preview"] = result.translation[:120]
    prefix = "[TRANSLATION WARNING]" if result.review != "PASS" else "[TRANSLATION]"
    print(prefix, json.dumps(payload, ensure_ascii=False), file=sys.stderr, flush=True)


def log_failure(
    *,
    kind: str,
    target: str,
    context: str,
    error: Exception,
    attempt: int,
    page: int | str | None = None,
    model: str = "",
    raw: str | None = None,
    batch_index: int | None = None,
    batch_total: int | None = None,
) -> None:
    payload: dict[str, Any] = {
        "request_type": kind,
        "page": page,
        "model": model,
        "attempt": attempt,
        "error_type": type(error).__name__,
        "error": str(error)[:800],
        "source_length": len(target),
        "context_length": len(context),
    }
    if raw is not None:
        payload["response_length"] = len(raw)
    if batch_index is not None:
        payload["batch"] = batch_index
    if batch_total is not None:
        payload["batch_total"] = batch_total
    if isinstance(error, json.JSONDecodeError):
        payload.update({"line": error.lineno, "column": error.colno, "position": error.pos})
    if raw is not None and os.getenv("TRANSLATION_DEBUG", "").strip().lower() in {"1", "true", "yes"}:
        payload["response_preview"] = raw[:1200]
        if isinstance(error, json.JSONDecodeError):
            start = max(0, error.pos - 240)
            end = min(len(raw), error.pos + 240)
            payload["response_error_context_start"] = start
            payload["response_error_context"] = raw[start:end]
    print(
        "[TRANSLATION WARNING]",
        json.dumps(payload, ensure_ascii=False),
        file=sys.stderr,
        flush=True,
    )


def _batch_generate(
    backend: GenerationBackend,
    system_prompt: str,
    prompt: str,
    *,
    kind: str,
    stage_label: str,
    parser: Any,
    schema: dict[str, Any] | None = None,
    page: int | str | None = None,
    max_completion_tokens: int = 1024,
) -> Any:
    # Kept as a thin named wrapper because translation/review call sites need
    # explicit request types and separate schemas in their logs.
    del stage_label
    return _call_once(
        backend,
        system_prompt,
        prompt,
        kind=kind,
        page=page,
        parser=parser,
        max_completion_tokens=max_completion_tokens,
        schema_name=kind,
        schema=schema,
    )


def generate_candidate(
    backend: GenerationBackend,
    system_prompt: str,
    prompt: str,
    *,
    kind: str,
    target: str,
    context: str,
) -> str:
    del target, context

    def parse(raw: str) -> str:
        candidate = clean_translation(raw)
        if not candidate:
            raise ValueError("translation produced empty output")
        return candidate

    return _call_once(
        backend,
        system_prompt,
        prompt,
        kind=f"{kind}_translation",
        page=None,
        parser=parse,
        max_completion_tokens=256,
    )


def review_candidate(
    backend: GenerationBackend,
    *,
    kind: str,
    target: str,
    context: str,
    candidate: str,
) -> ReviewResult:
    prompt = reviewer_prompt(kind, context, target, candidate)
    review_error: Exception | None = None
    try:
        return _call_once(
            backend,
            REVIEWER_SYSTEM_PROMPT,
            prompt,
            kind=f"{kind}_review",
            page=None,
            parser=lambda raw: parse_review(raw, candidate),
            max_completion_tokens=384,
            schema_name="single_translation_review",
            schema=SINGLE_REVIEW_SCHEMA,
        )
    except Exception as exc:
        review_error = exc
        print(
            "[TRANSLATION REVIEW WARNING]",
            json.dumps(
                {
                    "request_type": f"{kind}_review",
                    "model": getattr(backend, "model", ""),
                    "error_type": type(exc).__name__,
                    "error": str(exc)[:800],
                    "source_length": len(target),
                    "context_length": len(context),
                },
                ensure_ascii=False,
            ),
            file=sys.stderr,
            flush=True,
        )
    return ReviewResult(
        passed=False,
        score=0.0,
        issues=[f"reviewer_failed: {review_error or 'unknown error'}"],
        corrected_translation=candidate,
        reviewer_failed=True,
    )


def deterministic_issues(source: str, translation: str) -> list[str]:
    issues: list[str] = []
    if not translation:
        issues.append("empty translation")
    if NUMBER_RE.findall(source) != NUMBER_RE.findall(translation):
        issues.append("numbers/dates/times changed")
    if PREFIX_RE.match(translation):
        issues.append("unexpected translation label")
    return issues


def translate_target(
    backend: GenerationBackend,
    *,
    kind: str,
    target: str,
    context: str,
    sentence: str = "",
) -> TranslationResult:
    system = TRANSLATOR_SYSTEM_PROMPT if kind == "sentence" else WORD_TRANSLATOR_SYSTEM_PROMPT
    prompt = sentence_prompt(context, target) if kind == "sentence" else word_prompt(context, sentence, target)
    candidate = generate_candidate(
        backend,
        system,
        prompt,
        kind=kind,
        target=target,
        context=context,
    )
    review = review_candidate(
        backend,
        kind=kind,
        target=target,
        context=context,
        candidate=candidate,
    )
    final = clean_translation(review.corrected_translation) or candidate
    issues = list(review.issues)
    issues.extend(item for item in deterministic_issues(target, final) if item not in issues)
    passed = review.passed and review.score >= 0.85 and not issues and not review.reviewer_failed
    return TranslationResult(
        translation=final,
        score=review.score,
        issues=issues,
        review="PASS" if passed else ("REVIEWER_FAILED" if review.reviewer_failed else "WARNING"),
    )


def build_review_items(
    items: list[dict[str, Any]],
    candidates: dict[str, dict[str, Any]],
) -> list[dict[str, Any]]:
    review_items: list[dict[str, Any]] = []
    for item in items:
        candidate = candidates[item["id"]]
        review_items.append(
            {
                "id": item["id"],
                "context": item["context"],
                "target_text": item["target_text"],
                "candidate_translation": candidate["translation"],
                "words": [
                    {
                        "id": word["id"],
                        "text": word["text"],
                        "candidate_meaning": candidate["words"][word["id"]]["meaning"],
                        "candidate_phonetic": candidate["words"][word["id"]]["phonetic"],
                    }
                    for word in item["words"]
                ],
            }
        )
    return review_items


def fallback_review(
    candidates: dict[str, dict[str, Any]]
) -> dict[str, dict[str, Any]]:
    return {
        segment_id: {
            "translation": candidate["translation"],
            "issues": [],
            "passed": True,
            "score": None,
            "words": {
                word_id: {
                    "meaning": word["meaning"],
                    "phonetic": word["phonetic"],
                    "issues": [],
                    "score": None,
                }
                for word_id, word in candidate["words"].items()
            },
        }
        for segment_id, candidate in candidates.items()
    }


def local_translate_candidates(
    backend: LocalMLXBackend,
    items: list[dict[str, Any]],
    expected: dict[str, set[str]],
    *,
    page: int | str | None,
    max_completion_tokens: int,
) -> dict[str, dict[str, Any]]:
    del expected
    word_count = sum(len(item["words"]) for item in items)
    print(
        json.dumps(
            {
                "event": "status",
                "message": f"本地整页翻译：{len(items)} 个片段，{word_count} 个单词；结果按输入位置绑定，不由模型生成 ID",
            },
            ensure_ascii=False,
        ),
        flush=True,
    )
    candidates = _local_structured_call(
        backend,
        LOCAL_TRANSLATOR_SYSTEM_PROMPT,
        local_translation_prompt(items),
        kind="page_translation",
        page=page,
        parser=lambda raw: parse_local_translation(raw, items),
        schema=LOCAL_TRANSLATION_SCHEMA,
        max_completion_tokens=min(
            max_completion_tokens,
            max(2048, 768 + word_count * 112 + len(items) * 192),
        ),
    )
    # Position-based parsing already rebuilds the real IDs from the OCR input.
    # Verify the final in-memory shape before reviewer/application.
    validate_complete_candidates(candidates, expected_for_items(items))
    return candidates


def local_review_candidates(
    backend: LocalMLXBackend,
    items: list[dict[str, Any]],
    candidates: dict[str, dict[str, Any]],
    *,
    page: int | str | None,
) -> tuple[dict[str, dict[str, Any]], bool]:
    try:
        reviewed = _local_structured_call(
            backend,
            LOCAL_REVIEWER_SYSTEM_PROMPT,
            local_review_prompt(items, candidates),
            kind="page_review",
            page=page,
            parser=lambda raw: parse_local_review(raw, items, candidates),
            schema=LOCAL_REVIEW_SCHEMA,
            max_completion_tokens=max(
                1024,
                256 + sum(len(item["words"]) for item in items) * 40 + len(items) * 64,
            ),
        )
        return reviewed, False
    except Exception as exc:
        # Review is quality enhancement only. The translator result has already
        # passed positional count/shape validation, so retain it and require
        # human review rather than discarding the whole page.
        print(
            "[TRANSLATION REVIEW WARNING]",
            json.dumps(
                {
                    "request_type": "page_review",
                    "page": page,
                    "model": getattr(backend, "model", ""),
                    "error_type": type(exc).__name__,
                    "error": str(exc)[:800],
                    "fallback": "kept_validated_local_translation",
                },
                ensure_ascii=False,
            ),
            file=sys.stderr,
            flush=True,
        )
        return fallback_review(candidates), True


def translate_page(content: dict[str, Any], backend: GenerationBackend) -> dict[str, Any]:
    raw_segments = content.get("segments", [])
    if not isinstance(raw_segments, list):
        raise ValueError("page JSON field segments must be an array")
    segments = [segment for segment in raw_segments if isinstance(segment, dict)]
    if not segments:
        print(json.dumps({"event": "progress", "stage": "done", "progress": 2, "total": 2}), flush=True)
        print(json.dumps({"translated": 0, "failed": 0}, ensure_ascii=False), flush=True)
        return content

    items, expected = _page_items(segments)
    page_number = content.get("page", content.get("page_no"))
    page_number = page_number if isinstance(page_number, (int, str)) else None
    word_count = sum(len(item["words"]) for item in items)
    segment_count = len(items)
    translation_token_budget = configured_translation_completion_tokens()
    review_token_budget = min(
        2048,
        max(384, 128 + word_count * 16 + segment_count * 24),
    )

    print(json.dumps({"event": "progress", "stage": "translator", "progress": 0, "total": 2}), flush=True)
    if isinstance(backend, LocalMLXBackend):
        candidates = local_translate_candidates(
            backend,
            items,
            expected,
            page=page_number,
            max_completion_tokens=translation_token_budget,
        )
        print(json.dumps({"event": "progress", "stage": "reviewer", "progress": 1, "total": 2}), flush=True)
        reviewed, review_failed = local_review_candidates(
            backend,
            items,
            candidates,
            page=page_number,
        )
    else:
        # Cloud policy stays intentionally strict: one page translation call,
        # one page review call, no automatic retries or model fallback.
        candidates = _batch_generate(
            backend,
            BATCH_TRANSLATOR_SYSTEM_PROMPT,
            batch_translation_prompt(items),
            kind="page_translation",
            stage_label="整页翻译",
            parser=lambda raw: parse_batch_translation(raw, expected),
            schema=BATCH_TRANSLATION_SCHEMA,
            page=page_number,
            max_completion_tokens=translation_token_budget,
        )
        print(json.dumps({"event": "progress", "stage": "reviewer", "progress": 1, "total": 2}), flush=True)
        review_items = build_review_items(items, candidates)
        review_failed = False
        try:
            reviewed = _batch_generate(
                backend,
                BATCH_REVIEWER_SYSTEM_PROMPT,
                batch_review_prompt(review_items),
                kind="page_review",
                stage_label="整页审核",
                parser=lambda raw: parse_batch_review(raw, candidates, expected),
                schema=BATCH_REVIEW_SCHEMA,
                page=page_number,
                max_completion_tokens=review_token_budget,
            )
        except Exception as exc:
            # A successful cloud translation is retained when only the review
            # response fails. There is still no retry and no automatic fallback.
            review_failed = True
            reviewed = fallback_review(candidates)
            print(
                "[TRANSLATION REVIEW WARNING]",
                json.dumps(
                    {
                        "request_type": "page_review",
                        "page": page_number,
                        "model": getattr(backend, "model", ""),
                        "error_type": type(exc).__name__,
                        "error": str(exc)[:800],
                        "fallback": "kept_page_translation",
                    },
                    ensure_ascii=False,
                ),
                file=sys.stderr,
                flush=True,
            )
    print(json.dumps({"event": "progress", "stage": "done", "progress": 2, "total": 2}), flush=True)

    # Coordinates, OCR confidence, IDs, images, and audio metadata are never
    # touched. Existing phonetics are never overwritten; only blanks may be
    # filled from the model's reviewed IPA value.
    translated = 0
    failed = 0
    phonetic_filled = 0
    phonetic_missing = 0
    for segment in segments:
        segment_id = str(segment["id"])
        result = reviewed[segment_id]
        segment["translation"] = result["translation"]
        segment_issues = list(result["issues"])
        segment_issues.extend(
            item
            for item in deterministic_issues(target_sentence(segment), result["translation"])
            if item not in segment_issues
        )
        if review_failed:
            review_status = "REVIEW_WARNING"
            if segment_issues:
                failed += 1
        elif result["passed"] and not segment_issues:
            review_status = "PASS"
        else:
            review_status = "WARNING"
            failed += 1
        translated += 1
        log_translation(
            kind="sentence",
            target=target_sentence(segment),
            context=next(item["context"] for item in items if item["id"] == segment_id),
            result=TranslationResult(result["translation"], result.get("score"), segment_issues, review_status),
        )
        words_by_id = {str(word.get("id", "")): word for word in segment.get("words", []) if isinstance(word, dict)}
        for word_id, word_result in result["words"].items():
            word = words_by_id[word_id]
            source = normalize_source_text(word.get("text", ""))
            word["meaning"] = word_result["meaning"]
            if not str(word.get("phonetic", "") or "").strip():
                phonetic = clean_phonetic(word_result.get("phonetic", ""))
                # A model occasionally echoes the English token instead of IPA.
                if phonetic and phonetic.casefold() != source.casefold():
                    word["phonetic"] = phonetic
                    phonetic_filled += 1
                else:
                    phonetic_missing += 1
            translated += 1
            if word_result["issues"]:
                failed += 1
            log_translation(
                kind="word",
                target=source,
                context=target_sentence(segment),
                result=TranslationResult(
                    word_result["meaning"],
                    word_result.get("score"),
                    word_result["issues"],
                    "REVIEW_WARNING" if review_failed else "PASS" if not word_result["issues"] else "WARNING",
                ),
            )

    print(
        json.dumps(
            {
                "translated": translated,
                "failed": failed,
                "phonetic_filled": phonetic_filled,
                "phonetic_missing": phonetic_missing,
                "review_warning": review_failed,
            },
            ensure_ascii=False,
        ),
        flush=True,
    )
    return content


def _required_env(name: str) -> str:
    value = os.getenv(name, "").strip()
    if not value:
        raise RuntimeError(f"{name} is not set")
    return value


def configured_backend(model_id: str = "") -> GenerationBackend:
    selected = (model_id or os.getenv("TRANSLATION_MODEL", "")).strip()
    if selected == "local-qwen3-4b-instruct-2507":
        return LocalMLXBackend()
    if not selected:
        selected = _required_env("TRANSLATION_MODEL")
    try:
        connect_timeout = float(os.getenv("TRANSLATION_CONNECT_TIMEOUT", "10"))
        read_timeout = float(os.getenv("TRANSLATION_READ_TIMEOUT", "90"))
    except ValueError as exc:
        raise RuntimeError("Invalid translation API timeout configuration") from exc
    if connect_timeout <= 0 or read_timeout <= 0:
        raise RuntimeError("Translation API timeouts must be positive")
    api_key = os.getenv("TRANSLATION_API_KEY", "").strip() or os.getenv("DASHSCOPE_API_KEY", "").strip()
    if not api_key:
        raise RuntimeError("TRANSLATION_API_KEY or DASHSCOPE_API_KEY is not set")
    base_url = os.getenv("TRANSLATION_API_BASE_URL", "").strip() or os.getenv("DASHSCOPE_BASE_URL", "").strip()
    if not base_url:
        raise RuntimeError("TRANSLATION_API_BASE_URL or DASHSCOPE_BASE_URL is not set")
    return OnlineLLMClient(
        base_url=base_url,
        api_key=api_key,
        model=selected,
        temperature=0.1,
        connect_timeout=connect_timeout,
        read_timeout=read_timeout,
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--model-id", default="")
    args = parser.parse_args()

    backend: GenerationBackend | None = None
    try:
        backend = configured_backend(args.model_id)
        content = json.loads(args.input.read_text(encoding="utf-8"))
        translated = translate_page(content, backend)
        args.output.write_text(
            json.dumps(translated, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
    except Exception as exc:
        raise SystemExit(str(exc)) from exc
    finally:
        if backend is not None:
            logger = getattr(backend, "log_summary", None)
            if callable(logger):
                logger()


if __name__ == "__main__":
    main()
