import {useEffect,useState} from 'react';
import {api,type Identity,type SiteConfig} from './api';

export default function Account(){
 const params=new URLSearchParams(location.search),initial=params.get('mode')||'login';
 const [mode,setMode]=useState(['login','register','forgot','reset','verify'].includes(initial)?initial:'login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[token,setToken]=useState(params.get('token')||''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[user,setUser]=useState<Identity|null>(null),[config,setConfig]=useState<SiteConfig|null>(null);
 useEffect(()=>{Promise.all([api<{user:Identity|null}>('/me'),api<SiteConfig>('/config')]).then(([m,c])=>{setUser(m.user);setConfig(c)}).catch(e=>setError(e.message))},[]);
 function switchMode(next:string){setMode(next);setError('');setMessage('');setPassword('');history.replaceState(null,'',`/account?mode=${next}`)}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await api<{message?:string}>(`/auth/${mode}`,{method:'POST',body:JSON.stringify({email,password,token})});if(mode==='login'){setUser((await api<{user:Identity}>('/me')).user);setMessage('登录成功')}else{setMessage(result.message||'操作成功');if(mode==='reset'||mode==='verify'){setMode('login');setToken('')}}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const labels:Record<string,string>={login:'登录',register:'注册',forgot:'找回密码',reset:'设置新密码',verify:'验证邮箱'};
 return <main className="account-shell"><a className="admin-brand" href="/">小小点读家 <span>账号中心</span></a><section className="account-card"><p className="eyebrow">每天读一点，英语更熟练</p><nav className="account-mode-switch" aria-label="登录或注册"><button className={mode==='login'?'active':''} onClick={()=>switchMode('login')}>登录</button><button className={mode==='register'?'active':''} onClick={()=>switchMode('register')}>注册</button></nav><h1>{user?'我的账号':labels[mode]}</h1>{error&&<p className="admin-error">{error}</p>}{message&&<p className="admin-success">{message}</p>}{user?<><p>{user.email}</p><a className="admin-primary" href="/">回到我的书架</a><button className="admin-secondary" onClick={async()=>{await api('/auth/logout',{method:'POST'});setUser(null)}}>退出登录</button></>:<form onSubmit={submit}>{['login','register','forgot'].includes(mode)&&<label>邮箱<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>}{['login','register','reset'].includes(mode)&&<label>密码<input type="password" required minLength={mode==='login'?undefined:10} value={password} onChange={e=>setPassword(e.target.value)}/></label>}{mode==='verify'&&<p>确认验证当前邮箱。</p>}<button className="admin-primary" disabled={busy}>{busy?'处理中…':labels[mode]}</button></form>} {!user&&<nav className="account-links"><button onClick={()=>switchMode(mode==='forgot'?'login':'forgot')}>{mode==='forgot'?'返回登录':'找回密码'}</button></nav>}<p className="admin-note">邮箱模式：{config?.email_mode||'读取中'}{config?.email_mode==='local'?'（邮件写入 .local/mail）':''}</p></section></main>
}
