import {useEffect,useState} from 'react';
import {api} from './api';

type Teacher={id:number;email:string;display_name:string;country:string;timezone:string;active:boolean;verified:boolean;bio:string;activation_email_sent?:boolean};
type Availability={weekday:number;start_minute:number;end_minute:number;active:boolean};
type Lesson={id:number;teacher_id:number;student_id:number;student_name:string;teacher_name:string;scheduled_start_at:string;scheduled_end_at:string;status:string;duration_minutes:number;teaching_seconds:number;cancel_reason:string};
const days=['周日','周一','周二','周三','周四','周五','周六'];
const time=(minute:number)=>`${Math.floor(minute/60).toString().padStart(2,'0')}:${(minute%60).toString().padStart(2,'0')}`;
const minute=(value:string)=>{const [h,m]=value.split(':').map(Number);return h*60+m};
const safeZone=(zone?:string)=>{try{new Intl.DateTimeFormat('en-US',{timeZone:zone||'Asia/Shanghai'});return zone||'Asia/Shanghai'}catch{return 'Asia/Shanghai'}};

export function AdminTeachers({canWrite,showStats}:{canWrite:boolean;showStats:boolean}){
 const [rows,setRows]=useState<Teacher[]>([]),[selected,setSelected]=useState<Teacher|null>(null),[availability,setAvailability]=useState<Availability[]>([]),[off,setOff]=useState<{start_at:string;end_at:string;reason:string}[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [statsMonth,setStatsMonth]=useState(new Date().toISOString().slice(0,7)),[stats,setStats]=useState<{completed_lessons:number;student_no_show:number;cancelled:number;teaching_seconds:number}|null>(null);
 const [form,setForm]=useState({email:'',display_name:'',country:'',timezone:'Europe/London',bio:''}),[day,setDay]=useState(1),[start,setStart]=useState('09:00'),[end,setEnd]=useState('12:00'),[offStart,setOffStart]=useState(''),[offEnd,setOffEnd]=useState(''),[offReason,setOffReason]=useState('');
 const load=()=>api<Teacher[]|null>('/admin/teachers').then(v=>setRows(v??[])).catch(e=>setError(e.message));
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!selected)return;void api<Availability[]|null>(`/admin/teachers/${selected.id}/availability`).then(v=>setAvailability(v??[])).catch(e=>setError(e.message));void api<typeof off|null>(`/admin/teachers/${selected.id}/time-off`).then(v=>setOff(v??[])).catch(e=>setError(e.message))},[selected?.id]);
 useEffect(()=>{if(!selected||!showStats)return;void api<typeof stats>(`/admin/teachers/${selected.id}/statistics?month=${statsMonth}`).then(setStats).catch(e=>setError(e.message))},[selected?.id,statsMonth,showStats]);
 async function create(e:React.FormEvent){e.preventDefault();if(!canWrite){setError('当前账号没有外教编辑权限');return}setError('');try{const row=await api<Teacher>('/admin/teachers',{method:'POST',body:JSON.stringify(form)});setNotice(row.activation_email_sent?'外教已创建，激活邮件已发送。':'外教已创建，但激活邮件未送达，请重发。');setForm({email:'',display_name:'',country:'',timezone:'Europe/London',bio:''});await load()}catch(err){setError((err as Error).message)}}
 async function resend(t:Teacher){try{await api('/teacher/auth/forgot',{method:'POST',body:JSON.stringify({email:t.email})});setNotice('设置密码邮件已重发。')}catch(e){setError((e as Error).message)}}
 async function saveTeacher(e:React.FormEvent){e.preventDefault();if(!selected)return;try{const updated=await api<Teacher>(`/admin/teachers/${selected.id}`,{method:'PATCH',body:JSON.stringify({display_name:selected.display_name,country:selected.country,timezone:selected.timezone,bio:selected.bio})});setSelected(updated);await load();setNotice('外教资料已保存')}catch(err){setError((err as Error).message)}}
 async function toggle(t:Teacher){try{await api(`/admin/teachers/${t.id}`,{method:'PATCH',body:JSON.stringify({active:!t.active})});await load()}catch(e){setError((e as Error).message)}}
 async function saveAvailability(rows:Availability[]){if(!selected)return;try{await api(`/admin/teachers/${selected.id}/availability`,{method:'POST',body:JSON.stringify({rows})});setAvailability(rows);setNotice('开放时间已保存')}catch(e){setError((e as Error).message)}}
 async function addOff(e:React.FormEvent){e.preventDefault();if(!selected)return;try{await api(`/admin/teachers/${selected.id}/time-off`,{method:'POST',body:JSON.stringify({start_at:new Date(offStart).toISOString(),end_at:new Date(offEnd).toISOString(),reason:offReason})});setOff((await api<typeof off|null>(`/admin/teachers/${selected.id}/time-off`))??[]);setNotice('请假已登记')}catch(err){setError((err as Error).message)}}
 return <><div className="admin-panel"><h2>新建外教</h2><p>创建后会发送设置密码邮件。</p>{error&&<p className="admin-error">{error}</p>}{notice&&<p className="admin-success">{notice}</p>}<form className="form-grid" onSubmit={create}><label>邮箱<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>姓名<input required value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/></label><label>国家<input value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/></label><label>时区<input required value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}/></label><button className="admin-primary">创建外教</button></form></div>
 <div className="admin-panel"><h2>外教列表</h2><div className="table-scroll"><table><thead><tr><th>姓名</th><th>邮箱</th><th>国家/时区</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.map(t=><tr key={t.id}><td>{t.display_name}</td><td>{t.email}</td><td>{t.country}<br/>{t.timezone}</td><td>{t.active?(t.verified?'启用':'待激活'):'停用'}</td><td><button onClick={()=>setSelected(t)}>排班/请假</button> <button onClick={()=>void toggle(t)}>{t.active?'停用':'启用'}</button> {!t.verified&&<button onClick={()=>void resend(t)}>重发邮件</button>}</td></tr>)}</tbody></table></div></div>
 {selected&&<div className="admin-panel"><h2>{selected.display_name} · 资料与课时</h2><form className="form-grid" onSubmit={saveTeacher}><label>姓名<input required value={selected.display_name} onChange={e=>setSelected({...selected,display_name:e.target.value})}/></label><label>国家<input value={selected.country} onChange={e=>setSelected({...selected,country:e.target.value})}/></label><label>时区<input required value={selected.timezone} onChange={e=>setSelected({...selected,timezone:e.target.value})}/></label><label>简介<input value={selected.bio||''} onChange={e=>setSelected({...selected,bio:e.target.value})}/></label><button className="admin-primary">保存资料</button></form><label>统计月份 <input type="month" value={statsMonth} onChange={e=>setStatsMonth(e.target.value)}/></label>{stats&&<p>已完成 {stats.completed_lessons} 节 · 实际授课 {Math.round(stats.teaching_seconds/60)} 分钟 · 学生缺席 {stats.student_no_show} 节 · 取消 {stats.cancelled} 节</p>}</div>}
 {selected&&<div className="admin-panel"><h2>{selected.display_name} · 开放时间</h2><p>按 {selected.timezone} 当地时间设置，每段最多到当天 24:00。</p><div className="form-grid"><label>星期<select value={day} onChange={e=>setDay(Number(e.target.value))}>{days.map((d,i)=><option key={d} value={i}>{d}</option>)}</select></label><label>开始<input type="time" step="1800" value={start} onChange={e=>setStart(e.target.value)}/></label><label>结束<input type="time" step="1800" value={end} onChange={e=>setEnd(e.target.value)}/></label><button className="admin-primary" onClick={()=>void saveAvailability([...availability,{weekday:day,start_minute:minute(start),end_minute:minute(end),active:true}])}>添加时段</button></div><div className="lesson-list">{availability.map((a,i)=><article key={`${a.weekday}-${a.start_minute}-${i}`}><strong>{days[a.weekday]} {time(a.start_minute)}–{time(a.end_minute)}</strong><button onClick={()=>void saveAvailability(availability.filter((_,j)=>i!==j))}>移除</button></article>)}</div><h3>登记请假</h3><form className="form-grid" onSubmit={addOff}><label>开始<input type="datetime-local" required value={offStart} onChange={e=>setOffStart(e.target.value)}/></label><label>结束<input type="datetime-local" required value={offEnd} onChange={e=>setOffEnd(e.target.value)}/></label><label>原因<input value={offReason} onChange={e=>setOffReason(e.target.value)}/></label><button className="admin-primary">登记</button></form>{off.map(v=><p key={v.start_at}>{new Date(v.start_at).toLocaleString()} 至 {new Date(v.end_at).toLocaleString()} · {v.reason}</p>)}</div>}</>;
}

export function AdminLessons({canWrite,canCancel,canReadStudents}:{canWrite:boolean;canCancel:boolean;canReadStudents:boolean}){
 const [teachers,setTeachers]=useState<Teacher[]>([]),[students,setStudents]=useState<{id:number;email:string}[]>([]),[rows,setRows]=useState<Lesson[]>([]),[teacherID,setTeacherID]=useState(0),[studentID,setStudentID]=useState(0),[studentZone,setStudentZone]=useState('Asia/Shanghai'),[start,setStart]=useState(''),[note,setNote]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=()=>api<Lesson[]|null>('/admin/lessons').then(v=>setRows(v??[])).catch(e=>setError(e.message));
 useEffect(()=>{void api<Teacher[]|null>('/admin/teachers').then(value=>{const v=value??[];setTeachers(v);if(v.length)setTeacherID(v[0].id)}).catch(e=>setError(e.message));if(canReadStudents)void api<typeof students|null>('/admin/students').then(value=>{const v=value??[];setStudents(v);if(v.length)setStudentID(v[0].id)}).catch(e=>setError(e.message));void load()},[canReadStudents]);
 useEffect(()=>{if(studentID&&canReadStudents)void api<{timezone:string}>(`/admin/students/${studentID}/profile`).then(v=>setStudentZone(v.timezone||'Asia/Shanghai')).catch(()=>{})},[studentID,canReadStudents]);
 const when=start?new Date(start):null,t=teachers.find(v=>v.id===teacherID);
 async function create(e:React.FormEvent){e.preventDefault();if(!canWrite||!canReadStudents){setError('当前账号没有排课所需权限');return}setError('');try{await api('/admin/lessons',{method:'POST',body:JSON.stringify({student_id:studentID,teacher_id:teacherID,start_at:new Date(start).toISOString(),duration_minutes:30,note,idempotency_key:crypto.randomUUID()})});setNotice('排课成功');await load()}catch(err){setError((err as Error).message)}}
 async function cancel(id:number){if(!canCancel){setError('当前账号没有取消课程权限');return}const reason=window.prompt('请输入取消原因');if(reason===null)return;try{await api(`/admin/lessons/${id}/cancel`,{method:'POST',body:JSON.stringify({reason})});await load()}catch(e){setError((e as Error).message)}}
 return <><div className="admin-panel"><h2>手工排课</h2>{error&&<p className="admin-error">{error}</p>}{notice&&<p className="admin-success">{notice}</p>}{canWrite&&canReadStudents?<><form className="form-grid" onSubmit={create}><label>学生<select value={studentID} onChange={e=>setStudentID(Number(e.target.value))}>{students.map(x=><option key={x.id} value={x.id}>{x.email}</option>)}</select></label><label>外教<select value={teacherID} onChange={e=>setTeacherID(Number(e.target.value))}>{teachers.map(x=><option key={x.id} value={x.id}>{x.display_name}</option>)}</select></label><label>开始时间（本机）<input type="datetime-local" step="1800" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>备注<input value={note} onChange={e=>setNote(e.target.value)}/></label><button className="admin-primary" disabled={!studentID||!teacherID}>创建课程</button></form>{when&&<p>学生当地：{new Intl.DateTimeFormat('zh-CN',{timeZone:safeZone(studentZone),dateStyle:'medium',timeStyle:'short'}).format(when)}（{studentZone}）<br/>外教当地：{new Intl.DateTimeFormat('zh-CN',{timeZone:safeZone(t?.timezone),dateStyle:'medium',timeStyle:'short'}).format(when)}（{t?.timezone}）</p>}</>:<p>当前账号没有排课所需的课程编辑与学生查看权限。</p>}</div><div className="admin-panel"><h2>课程列表</h2><div className="table-scroll"><table><thead><tr><th>时间</th><th>学生</th><th>外教</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.map(l=><tr key={l.id}><td>{new Date(l.scheduled_start_at).toLocaleString()}</td><td>{l.student_name||l.student_id}</td><td>{l.teacher_name||l.teacher_id}</td><td>{l.status}{l.status==='completed'&&` · ${Math.round(l.teaching_seconds/60)} 分钟`}{l.cancel_reason&&<small> · {l.cancel_reason}</small>}</td><td>{canCancel&&['scheduled','in_progress'].includes(l.status)&&<button onClick={()=>void cancel(l.id)}>取消课程</button>}</td></tr>)}</tbody></table></div></div></>;
}
