import {useEffect,useState} from 'react';
import {APIError} from './api';

export type TeacherLanguage='en'|'zh';
const key='xiaov2-teacher-language';
const changeEvent='xiaov2-teacher-language-change';
export function teacherLanguage():TeacherLanguage{return localStorage.getItem(key)==='zh'?'zh':'en'}
export function useTeacherLanguage(){
 const [language,setLanguage]=useState<TeacherLanguage>(teacherLanguage);
 useEffect(()=>{const sync=()=>setLanguage(teacherLanguage());window.addEventListener(changeEvent,sync);window.addEventListener('storage',sync);return()=>{window.removeEventListener(changeEvent,sync);window.removeEventListener('storage',sync)}},[]);
 return language;
}
export function setTeacherLanguage(language:TeacherLanguage){localStorage.setItem(key,language);window.dispatchEvent(new Event(changeEvent))}
export function TeacherLanguageSwitch(){const language=useTeacherLanguage();useEffect(()=>{const previous=document.documentElement.lang;document.documentElement.lang=language==='en'?'en':'zh-CN';return()=>{document.documentElement.lang=previous}},[language]);return <div className="teacher-language-switch" role="group" aria-label="Language / 语言"><button type="button" aria-pressed={language==='en'} onClick={()=>setTeacherLanguage('en')}>EN</button><button type="button" aria-pressed={language==='zh'} onClick={()=>setTeacherLanguage('zh')}>中文</button></div>}

const english:Record<string,string>={
 '外教工作台':'Teacher workspace','首页':'Home','我的课程':'My classes','我的课时':'Teaching hours','我的资料':'My profile','退出登录':'Log out',
 '外教登录':'Teacher sign in','找回密码':'Forgot password','设置密码':'Set password','邮箱':'Email','密码':'Password','处理中…':'Processing…','确认':'Continue','返回登录':'Back to sign in','操作成功':'Done','请查收密码重置邮件':'Check your email for the password reset link.','正在加载外教工作台…':'Opening teacher workspace…',
 '今天的课程':"Today's classes",'今天':'Today','本月已完成':'Completed this month','授课时间':'Teaching time','节课':' classes','节':' classes','分钟':' min','学生':'Student','待上课':'Scheduled','上课中':'In progress','已完成':'Completed','老师未参加':'Teacher absent','学生未参加':'Student absent','已取消':'Cancelled','已过期':'Expired','实际共同在线':'Time together','取消原因：':'Cancellation reason: ','设备检测 / 进入课堂 →':'Device check / Enter classroom →','暂无课程。':'No classes yet.',
 '月份':'Month','实际授课':'Actual teaching','学生缺席':'Student absent','取消':'Cancelled','资料已保存':'Profile saved','姓名':'Name','国家':'Country','个人简介':'Bio','保存资料':'Save profile',
 '我的教学安排':'TEACHING SCHEDULE','按中国时间查看每天的排班与预约。':'View your daily schedule and bookings in China time.','选择日期':'Choose date','前一天':'Previous day','后一天':'Next day','正在读取排班…':'Loading schedule…','个时段':' slots','个有预约':' booked','正在加载当天排班…':'Loading today’s schedule…','当天没有排班时段':'No teaching slots that day','可以选择其他日期查看；如需调整排班，请联系管理员。':'Choose another date, or contact the administrator to change your schedule.','有预约':'Booked','请假休息':'Time off','已过时段':'Past','暂无预约':'Available','查看预约详情':'View booking details','等待学生预约':'Waiting for a student booking','该时段不开放预约':'This slot is unavailable','该时段没有预约':'No booking for this slot',
 '返回排班':'Back to schedule','课程预约':'CLASS BOOKING','预约详情':'Booking details','查看学生与上课安排。':'View the student and class arrangements.','正在加载预约详情…':'Loading booking details…','预约编号':'Booking #','预约学生':'Student','上课日期':'Class date','上课时间':'Class time','课程时长':'Class duration','课程状态':'Class status','预约备注':'Booking note','取消原因':'Cancellation reason','课前设备检测 / 进入课堂':'Device check / Enter classroom',
 '课前设备检测':'Pre-class device check','确认摄像头、麦克风和扬声器可用，再进入课堂。':'Check your camera, microphone, and speaker before entering the classroom.','本地调试模式：允许提前进入课堂，课程结束后仍不可进入。':'Local debug mode: early entry is allowed until the class ends.','检测中':'Checking','可使用':'Available','不可用':'Unavailable','待检测':'Not tested','摄像头':'Camera','麦克风':'Microphone','扬声器':'Speaker','默认摄像头':'Default camera','默认麦克风':'Default microphone','正在测试…':'Testing…','测试扬声器':'Test speaker','网络：':'Network: ','可用':'Available','毫秒':'ms','进入课堂':'Enter classroom','上课前 10 分钟可进入':'Available 10 minutes before class','正在检测摄像头…':'Checking camera…','摄像头不可用':'Camera unavailable','服务暂不可用':'Service unavailable','请使用 HTTPS 或 localhost 打开课堂':'Open the classroom over HTTPS or localhost','摄像头检测失败：':'Camera check failed: ','无法访问摄像头':'Cannot access camera','未检测到可用摄像头':'No working camera found','麦克风检测失败':'Microphone check failed','麦克风检测失败：':'Microphone check failed: ','未检测到可用麦克风':'No working microphone found',
 '画笔':'Pen','文字':'Text','矩形':'Rectangle','圆形':'Ellipse','橡皮擦':'Eraser','选择':'Select','清空本页':'Clear page','课堂白板暂不可用':'Whiteboard unavailable','重试连接':'Retry connection','正在准备互动白板':'Preparing the whiteboard','连接成功后，就可以一起书写和标注。':'Once connected, you can write and annotate together.','连接超时，请重试；如果仍失败，请检查网络连接。':'Connection timed out. Retry and check your network.','教师中心':'Teacher center','学习中心':'Learning center','1v1 外教课堂':'1-on-1 English classroom','正在加载课堂…':'Loading classroom…','正在连接':'Connecting','连接中':'Connecting','网络良好':'Network good','正在重连':'Reconnecting','剩余':'Remaining','课程已结束，正在退出':'Class ended. Leaving…','离开课堂':'Leave classroom','返回课程':'Back to classes','互动白板':'Interactive whiteboard','课堂暂时无法进入':'Classroom unavailable','正在准备课堂':'Preparing classroom','课堂资源加载后，即可开始上课。':'Your class will start when the resources are ready.','我的':'My','我':'Me','对方':'Other participant','对方视频':'Other participant','视频小窗，点击切换大小':' video window. Click to swap sizes.','大视频，点击切换大小':' large video. Click to swap sizes.','点击切换大小，拖动调整位置':'Click to swap sizes; drag to move','点击切换视频大小':'Click to swap video sizes','等待对方':'Waiting for participant','摄像头已关闭':'Camera off','正在开启摄像头':'Starting camera','点击切换大小':'Click to swap sizes','等待对方加入课堂':'Waiting for the other participant','连接成功后，视频会显示在这里。':'The video will appear here once connected.','开启麦克风':'Turn on microphone','关闭麦克风':'Turn off microphone','开启摄像头':'Turn on camera','关闭摄像头':'Turn off camera','停止共享':'Stop sharing','共享屏幕':'Share screen','课堂连接即将结束':'Classroom connection will end soon'
};
export function teacherText(language:TeacherLanguage,chinese:string){return language==='zh'?chinese:english[chinese]??chinese}
export function teacherStatus(language:TeacherLanguage,status:string){const names:Record<string,string>={scheduled:'待上课',in_progress:'上课中',completed:'已完成',teacher_no_show:'老师未参加',student_no_show:'学生未参加',cancelled:'已取消',expired:'已过期'};return teacherText(language,names[status]??status)}
export function teacherDate(language:TeacherLanguage,value:string){return new Intl.DateTimeFormat(language==='en'?'en-US':'zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date(value))}
export function teacherDateTime(language:TeacherLanguage,value:string){return new Intl.DateTimeFormat(language==='en'?'en-US':'zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(value))}
export function teacherClassCount(language:TeacherLanguage,count:number){return language==='en'?`${count} ${count===1?'class':'classes'}`:`${count} 节`}
const englishErrors:Record<string,string>={
 '邮箱或密码错误':'Incorrect email or password.','尝试次数过多，请稍后再试':'Too many attempts. Please try again later.','账号已停用':'This account is disabled.','请先完成邮箱验证':'Please verify your email first.','请先登录':'Please sign in.','账号类型无效':'Invalid account type.','请求过于频繁，请稍后再试':'Too many requests. Please try again later.','重置链接无效，或密码不足10个字符':'The reset link is invalid, or the password is shorter than 10 characters.','重置链接无效或已过期':'The reset link is invalid or has expired.','无权查看此排班':'You cannot view this schedule.','日期格式无效':'Invalid date.','月份格式无效':'Invalid month.','无权进入此课堂':'You cannot enter this classroom.','课程已经结束':'This class has ended.','当前不在上课时间':'It is not yet time for this class.','请使用 HTTPS 或 localhost 打开课堂':'Open the classroom over HTTPS or localhost.','未检测到可用摄像头':'No working camera found.','摄像头不可用':'Camera unavailable.','麦克风检测失败':'Microphone check failed.','未检测到可用麦克风':'No working microphone found.','课堂连接即将结束':'The classroom connection will end soon.','连接超时，请重试；如果仍失败，请检查网络连接。':'Connection timed out. Retry and check your network.'
};
export function teacherError(language:TeacherLanguage,error:unknown):string{
 const message=error instanceof Error?error.message:String(error);
 if(language==='zh'||!/\p{Script=Han}/u.test(message))return message;
 if(englishErrors[message])return englishErrors[message];
 for(const prefix of ['摄像头检测失败：','麦克风检测失败：'])if(message.startsWith(prefix))return `${teacherText(language,prefix)}${teacherError(language,message.slice(prefix.length))}`;
 if(error instanceof APIError){if(error.status===401)return 'Please sign in again.';if(error.status===403)return 'You do not have access to this class or action.';if(error.status===404)return 'The requested information was not found.';if(error.status===409)return 'This action conflicts with the current schedule. Please refresh and try again.'}
 return 'Something went wrong. Please try again.';
}
